# -*- coding: utf-8 -*-
# Sammlung „China“ (https://www.instagram.com/traveler__story/saved/china/17927233700798988/), 34 Posts.
# Spots: (Name, lat, lng, ungefähr?, Region, Kategorie, Posts, Hinweis)
# Posts: Nummer oder (Nummer, Slide) – Slide = Karussell-Bild, das genau diesen Ort zeigt.
# Post ohne Slide bei Sammel-Posts → nur „erwähnt in“, kein Foto (Titelbild zeigt meist einen anderen Ort).
POSTS = {
 1: ("hanontheroad", "p", "DeKUZY_k8EI"), 2: ("da_frames", "p", "Dd9L7iNJYFG"), 3: ("picn2k", "p", "DdEKV0ZCTq5"),
 4: ("nateinthewild", "reel", "DdpI6HuSyzy"), 5: ("samkolder", "reel", "Ddtwe45NY5j"), 6: ("nandokanarski", "reel", "DdWGg6qhvtE"),
 7: ("scotthowes", "p", "DdA4hImlOyb"), 8: ("jaysonrobertson", "p", "Ddl0op5FI_s"), 9: ("nateinthewild", "p", "DdbVoDMlRoY"),
 10: ("sjoerdbracke", "p", "DdJoIXXDCaY"), 11: ("nateinthewild", "p", "DdXg4t2GDJp"), 12: ("abeastinside", "reel", "DZga_rhNIWy"),
 13: ("llittlepig", "p", "DcdpJbZkkKN"), 14: ("alvinzhuxiyao", "p", "DcyCL4RD7-D"), 15: ("long.explorer", "p", "DcjMMWjtLLZ"),
 16: ("beautifuldestinations", "p", "Dcowt_bjmQ4"), 17: ("abeastinside", "reel", "Dc3DW5My9rU"), 18: ("chinawithelliott", "reel", "DZzuJp4OSP5"),
 19: ("portra_papi", "p", "DcWcfcTlAgw"), 20: ("saamjohnson_", "reel", "Db3BY92zda9"), 21: ("yantastic", "p", "DcIsDePCaxD"),
 22: ("yantastic", "p", "Db0JN3viXxs"), 23: ("yantastic", "p", "DbpsOzNCTDq"), 24: ("lifewithelliott", "reel", "DajVePfRtny"),
 25: ("beautifuldestinations", "reel", "Da5mrX6xtEd"), 26: ("chrisburkard", "p", "DXpjqO-Ei7T"), 27: ("lifewithelliott", "reel", "DWRbAhzETzA"),
 28: ("heykelseyj", "p", "DU0_ZiHj2jE"), 29: ("ruepush", "p", "DTWgwPiEvGy"), 30: ("chinny_photography", "p", "DSos799Dwm0"),
 31: ("chema.bal", "p", "DS0pYcckp4D"), 32: ("watschinger_lukas", "p", "DRE0E88DD0o"), 33: ("sjoerdbracke", "p", "DQmZY5ejLTt"),
 34: ("marc.hennige", "p", "C0o73svNagn"),
}

# Posts ohne Spot, die zu einer anderen Kartenregion gehören (13 = Taxis in Hongkong)
UNPLACED_REGION = {13: "hk"}

SPOTS = [
 # Hunan
 ("Zhangjiajie National Forest Park 张家界国家森林公园", 29.3499, 110.4352, True, "Wulingyuan, Hunan", "Natur",
  [1, 6, 15, 24, 31, 32, (30, 7)], "„Avatar“-Felssäulen. 2 Tage einplanen + 1 Puffertag; Seilbahn lohnt sich; beste Zeit April oder Juni–Aug (Nebel in den Tälern). Abseits der Hauptwege suchen."),
 ("Tianmen Mountain 天门山", 29.0499, 110.4789, False, "Zhangjiajie, Hunan", "Natur",
  [1], "1 Tag einplanen, Seilbahn direkt ab der Stadt."),
 ("Furong Town 芙蓉镇", 28.7731, 109.9819, False, "Yongshun, Hunan", "Dorf",
  [(30, 1)], "Dorf am Wasserfall, nachts beleuchtet."),
 ("Fenghuang Ancient Town 凤凰古城", 27.9509, 109.5998, False, "Xiangxi, Hunan", "Dorf",
  [(30, 4), 10, 33], "Stelzenhäuser am Tuo-Fluss, abends beleuchtet."),
 # Guizhou
 ("Xijiang Qianhu Miao Village 西江千户苗寨", 26.4955, 108.1702, False, "Leishan, Guizhou", "Dorf",
  [2, (21, 5)], "Größtes Miao-Dorf: Holz-Stelzenhäuser am Hang; Aussichtspunkte oberhalb."),
 ("Fenglin Buyi / Wanfenglin 峰林布依 · 万峰林", 25.0170, 104.9211, True, "Xingyi, Guizhou", "Natur",
  [3], "Pagodendorf am grünen Fluss zwischen Karstkegeln."),
 ("Jilong Castle 吉隆堡", 24.920389, 105.013147, False, "Xingyi, Guizhou", "Architektur",
  [28], "Märchenschloss-Hotel zwischen Karstbergen."),
 ("Fanjingshan 梵净山", 27.9100, 108.6917, False, "Tongren, Guizhou", "Tempel",
  [26], "Zwei Tempel auf der Felsnadel „Red Clouds Golden Summit“; ca. 9.000 Stufen (Seilbahn bis fast oben)."),
 # Guangxi
 ("Guilin & Li River 桂林 · 漓江", 25.2780, 110.2911, True, "Guilin, Guangxi", "Natur",
  [4], "Drohnen-Reel „What my drone saw in China“."),
 ("Xingping – Kormoranfischer am Li River 兴坪", 24.9198, 110.5278, True, "Yangshuo, Guangxi", "Dorf",
  [7], "Klassisches Motiv: Fischer mit Kormoranen auf dem Bambusfloß."),
 ("Xianggong Hill 相公山", 24.9258, 110.4790, False, "Yangshuo, Guangxi", "Aussicht",
  [9], "Sonnenaufgang über der Li-River-Schleife – früh los (Wecker 3:30)."),
 ("Yangshuo Karstlandschaft 阳朔", 24.8630, 110.4872, True, "Yangshuo, Guangxi", "Natur",
  [11, 10, 33, (21, 7)], "Karstkegel in endlosen Schichten, Sonnenaufgang mit Wasserbüffeln an der Steinbrücke."),
 # Chongqing
 ("Liziba Station 李子坝 – Monorail durchs Haus", 29.5557, 106.5339, False, "Yuzhong, Chongqing", "Architektur",
  [8], "Die Bahn fährt mitten durch das Wohnhaus; Aussichtsplattform unten an der Straße."),
 ("Hongyadong 洪崖洞", 29.565074, 106.575343, False, "Yuzhong, Chongqing", "Neon",
  [(14, 1)], "Abends beleuchtet; viele Treppen. Weitere Tipps im Post: Linhua Road Wohnkomplex, Wulong, Eling-Brücke."),
 ("Qiansimen Bridge 千厮门大桥", 29.565378, 106.576378, False, "Yuzhong, Chongqing", "Neon",
  [20], "Rote Fachwerkbrücke mit Skyline, nachts."),
 ("Kuixing Building 魁星楼", 29.5633, 106.5699, True, "Jiefangbei, Chongqing", "Architektur",
  [14], "Das Erdgeschoss ist zugleich der 22. Stock."),
 ("Chongqing Skyline & Rooftops 解放碑", 29.5578, 106.5771, True, "Jiefangbei, Chongqing", "Neon",
  [12, 17, (30, 3), (30, 5), 5], "Cyberpunk-Blick von Dächern; ab ca. 20 Uhr geht das Licht an."),
 ("Hongen Temple 鸿恩寺", 29.5728, 106.5029, True, "Jiangbei, Chongqing", "Tempel",
  [19], "Laternenweg zur Pagode (Ort nach Bild geschätzt)."),
 ("Three Natural Bridges 天生三桥", 29.4399, 107.7863, False, "Wulong, Chongqing", "Natur",
  [27], "3 h ab Chongqing; 1 h Rundweg, Glas-Aufzug hinunter. Tagestour: 7 Uhr los, 15 Uhr zurück."),
 # Shanghai
 ("Dongchangzhi Rd × Lushun Rd 东长治路旅顺路", 31.2518, 121.4923, False, "Hongkou, Shanghai", "Street",
  [(21, 3)], "North-Bund-Streetfoto-Spot: Alltag vor Oriental Pearl Tower und Shanghai Tower."),
 ("Waibaidu Bridge & Suzhou Creek 外白渡桥", 31.245307, 121.485744, False, "Huangpu, Shanghai", "Aussicht",
  [22], "Blick über die Mündung des Suzhou Creek auf Lujiazui zur goldenen Stunde."),
 ("The Bund & Lujiazui 外滩 · 陆家嘴", 31.2402, 121.4979, False, "Huangpu, Shanghai", "Aussicht",
  [16], "Skyline abends, wenn alles beleuchtet ist."),
 ("Shanghai Tower Observation Deck 上海中心", 31.2356, 121.5012, False, "Lujiazui, Shanghai", "Aussicht",
  [34], "Sonnenuntergang über Oriental Pearl Tower und Huangpu-Bogen."),
 ("Shanghai Astronomy Museum 上海天文馆", 30.9151, 121.9226, False, "Lingang, Shanghai", "Architektur",
  [18], "Gut 1 h ab Zentrum, 2–4 h einplanen, Kuppel-Show direkt bei Ankunft buchen, vorher essen."),
 # Weitere
 ("Wangxian Valley 望仙谷", 28.682859, 117.810253, False, "Shangrao, Jiangxi", "Dorf",
  [29, (30, 10), 16], "Klippendorf; am späten Nachmittag kommen, nach Sonnenuntergang beleuchtet. Mit Shanghai kombinierbar (Schnellzug nach Shangrao)."),
 ("Huangshan 黄山", 30.1310, 118.1660, True, "Anhui", "Natur",
  [(30, 6)], ""),
 ("Huanglong National Park 黄龙", 32.7411, 103.8332, False, "Songpan, Sichuan", "Natur",
  [(30, 2), (30, 9)], "Kalksinter-Terrassen in Türkis."),
 ("Chengdu 成都", 30.5728, 104.0668, True, "Sichuan", "Neon",
  [(30, 8), (30, 11), (21, 17)], ""),
 ("Canton Tower 广州塔", 23.108783, 113.317961, False, "Guangzhou", "Neon",
  [(16, 1)], "Skyline am Perlfluss nach Einbruch der Dunkelheit."),
 ("Shenzhen Futian Skyline 平安金融中心", 22.536412, 114.050471, True, "Futian, Shenzhen", "Architektur",
  [25, 16], "Futuristische Skyline nach Einbruch der Dunkelheit; mit Guangzhou kombinierbar."),
 ("Qingdao Haitian Center 青岛海天中心", 36.0562, 120.3649, True, "Shinan, Qingdao", "Neon",
  [23, (21, 15)], "Gedrehter Turm, nachts beleuchtet, Blick vom Strand der Fushan-Bucht."),
 ("Temple of Heaven 天坛", 39.8799, 116.4029, False, "Beijing", "Tempel",
  [(21, 9)], "Halle der Ernteopfer mit blauem Rundtempel-Dach."),
 ("Guge Kingdom Ruins 古格王国遗址", 31.4653, 79.6699, False, "Zanda, Tibet", "Tempel",
  [(21, 11)], "Ruinenstadt im Westen Tibets."),
]

# Beliebtheit 1–5 (5 = Wahrzeichen, 4 = in vielen Guides, 3 = bei Fotografen bekannt)
POP = {
 "Zhangjiajie": (5, "Avatar-Berge, eines der bekanntesten Naturziele Chinas"),
 "Tianmen": (5, "Himmelstor & längste Seilbahn, Top-Attraktion"),
 "Furong": (4, "Wasserfall-Dorf, viral in sozialen Medien"),
 "Fenghuang": (5, "Berühmteste Altstadt Westhunans"),
 "Xijiang": (5, "Größtes Miao-Dorf, in allen Guizhou-Guides"),
 "Fenglin": (3, "Bei Fotografen bekannte Karstlandschaft"),
 "Jilong": (3, "Viral gewordenes Schloss-Hotel"),
 "Fanjingshan": (4, "UNESCO-Welterbe, ikonische Felsnadel"),
 "Guilin": (5, "Klassische Karstlandschaft, Li-River-Kreuzfahrt"),
 "Xingping": (4, "Motiv des 20-Yuan-Scheins, Kormoranfischer"),
 "Xianggong": (4, "Bekanntester Sonnenaufgangs-Spot am Li River"),
 "Yangshuo": (5, "Top-Ziel für Karstlandschaften"),
 "Liziba": (5, "Weltbekanntes Fotomotiv Chongqings"),
 "Hongyadong": (5, "Wahrzeichen Chongqings, „Chihiro“-Look"),
 "Qiansimen": (4, "Klassischer Nachtblick auf Hongyadong"),
 "Kuixing": (3, "Kurioses 8D-Gebäude, bei Bloggern beliebt"),
 "Chongqing Skyline": (4, "Cyberpunk-Skyline, viral"),
 "Hongen": (3, "Aussichtspagode über Chongqing"),
 "Three Natural": (5, "UNESCO-Karst, Transformers-Drehort"),
 "Dongchangzhi": (3, "Beliebter Streetfoto-Spot am North Bund"),
 "Waibaidu": (4, "Historische Stahlbrücke mit Skyline-Blick"),
 "The Bund": (5, "Shanghais berühmteste Skyline"),
 "Shanghai Tower": (5, "Höchstes Gebäude Chinas, Aussichtsdeck"),
 "Astronomy": (4, "Größtes Planetarium der Welt"),
 "Wangxian": (4, "Viral gewordenes Klippendorf"),
 "Huangshan": (5, "Berühmtestes Gebirge Chinas, UNESCO"),
 "Huanglong": (5, "UNESCO-Kalksinterterrassen"),
 "Chengdu": (4, "Pandas, Teehäuser, Nachtleben"),
 "Canton Tower": (5, "Wahrzeichen Guangzhous"),
 "Shenzhen": (4, "Moderne Skyline, Ping An Finance Centre"),
 "Qingdao": (3, "Neue Skyline an der Fushan-Bucht"),
 "Temple of Heaven": (5, "UNESCO-Welterbe in Beijing"),
 "Guge": (4, "Abgelegene Ruinenstadt, Fotografen-Traum"),
}
