# -*- coding: utf-8 -*-
# Sammlung „China“ (https://www.instagram.com/traveler__story/saved/china/17927233700798988/), 34 Posts.
# Spots: (Name, lat, lng, ungefähr?, Region, Kategorie, Posts, Hinweis)
# Posts: Nummer oder (Nummer, Slide) – Slide = Karussell-Bild, das genau diesen Ort zeigt.
# Post ohne Slide bei Sammel-Posts → nur „erwähnt in“, kein Foto (Titelbild zeigt meist einen anderen Ort).
POSTS = {
 1: ("hanontheroad", "p", "DeKUZY_k8EI"), 2: ("da_frames", "p", "Dd9L7iNJYFG"), 3: ("picn2k", "p", "DdEKV0ZCTq5"),
 4: ("nateinthewild", "reel", "DdpI6HuSyzy"), 5: ("samkolder", "reel", "Ddtwe45NY5j"), 6: ("nandokanarski", "reel", "DdWGg6qhvtE"),
 7: ("scotthowes", "p", "DdA4hImlOyb"), 8: ("jaysonrobertson", "p", "Ddl0op5FI_s"), 9: ("nateinthewild", "p", "DdbVoDMlRoY"),
 10: ("sjoerdbracke", "p", "DdJoIXXDCaY"), 11: ("nateinthewild", "p", "DdXg4t2GDJp"), 12: ("abeastinside", "reel", "DZga_rhNIWy"),
 13: ("llittlepig", "p", "DcdpJbZkkKN"), 14: ("alvinzhuxiyao", "p", "DcyCL4RD7-D"), 15: ("long.explorer", "p", "DcjMMWjtLLZ"),
 16: ("beautifuldestinations", "p", "Dcowt_bjmQ4"), 17: ("abeastinside", "reel", "Dc3DW5My9rU"), 18: ("chinawithelliott", "reel", "DZzuJp4OSP5"),
 19: ("portra_papi", "p", "DcWcfcTlAgw"), 20: ("saamjohnson_", "reel", "Db3BY92zda9"), 21: ("yantastic", "p", "DcIsDePCaxD"),
 22: ("yantastic", "p", "Db0JN3viXxs"), 23: ("yantastic", "p", "DbpsOzNCTDq"), 24: ("lifewithelliott", "reel", "DajVePfRtny"),
 25: ("beautifuldestinations", "reel", "Da5mrX6xtEd"), 26: ("chrisburkard", "p", "DXpjqO-Ei7T"), 27: ("lifewithelliott", "reel", "DWRbAhzETzA"),
 28: ("heykelseyj", "p", "DU0_ZiHj2jE"), 29: ("ruepush", "p", "DTWgwPiEvGy"), 30: ("chinny_photography", "p", "DSos799Dwm0"),
 31: ("chema.bal", "p", "DS0pYcckp4D"), 32: ("watschinger_lukas", "p", "DRE0E88DD0o"), 33: ("sjoerdbracke", "p", "DQmZY5ejLTt"),
 34: ("marc.hennige", "p", "C0o73svNagn"),
 # später über den Eingang hinzugefügt
 35: ("minghan1004", "p", "Dd89Lyxk2hN"), 36: ("minghan1004", "p", "Dd3zCGRkzl-"),
 37: ("throughlucaslens", "p", "DNNgh9LoqbE"), 38: ("wiwa_b", "p", "DIlCwlaRZWs"), 39: ("calvinohhh", "p", "DIVTVzqT1cw"),
 40: ("throughlucaslens", "p", "DI00NkJoK_k"), 41: ("dxj_chinatravel", "p", "DdiudFSEbF0"), 42: ("jjll_____", "p", "DTIJBGfk-5D"),
 43: ("tchob_tchob", "p", "DUhpvJVkzt2"), 44: ("hey.lirules", "p", "DZUUOwzjCOx"), 45: ("blackmobil", "p", "DdyoIZJmsct"),
 46: ("minghan1004", "p", "DGNwBTCzT1N"), 47: ("hanaleytravel", "p", "DRo8DqWCiXB"), 48: ("jasmine_pirsch", "p", "C78YwHjtoLk"),
 49: ("davidlazarphoto", "p", "DDo2-MdTeS2"), 50: ("wyzhou22", "p", "DEaHiq2pJaL"),
 51: ("blackmobil", "p", "DRj2euBD9iL"),
}

# Posts ohne Spot, die zu einer anderen Kartenregion gehören (13 = Taxis in Hongkong)
UNPLACED_REGION = {13: "hk"}

SPOTS = [
 # Hunan
 ("Zhangjiajie National Forest Park 张家界国家森林公园", 29.3499, 110.4352, True, "Wulingyuan, Hunan", "Natur",
  [1, 6, 15, 24, 31, 32, (30, 7)], "„Avatar“-Felssäulen. 2 Tage einplanen + 1 Puffertag; Seilbahn lohnt sich; beste Zeit April oder Juni–Aug (Nebel in den Tälern). Abseits der Hauptwege suchen."),
 ("Tianmen Mountain 天门山", 29.0499, 110.4789, False, "Zhangjiajie, Hunan", "Natur",
  [(1, 3)], "1 Tag einplanen, Seilbahn direkt ab der Stadt."),
 ("Furong Town 芙蓉镇", 28.7731, 109.9819, False, "Yongshun, Hunan", "Dorf",
  [(30, 1)], "Dorf am Wasserfall, nachts beleuchtet."),
 ("Fenghuang Ancient Town 凤凰古城", 27.9509, 109.5998, False, "Xiangxi, Hunan", "Dorf",
  [(30, 4), 10, 33], "Stelzenhäuser am Tuo-Fluss, abends beleuchtet."),
 # Guizhou
 ("Xijiang Qianhu Miao Village 西江千户苗寨", 26.4955, 108.1702, False, "Leishan, Guizhou", "Dorf",
  [2, (21, 5)], "Größtes Miao-Dorf: Holz-Stelzenhäuser am Hang; Aussichtspunkte oberhalb."),
 ("Fenglin Buyi / Wanfenglin 峰林布依 · 万峰林", 25.0170, 104.9211, True, "Xingyi, Guizhou", "Natur",
  [3], "Pagodendorf am grünen Fluss zwischen Karstkegeln."),
 ("Jilong Castle 吉隆堡", 24.920389, 105.013147, False, "Xingyi, Guizhou", "Architektur",
  [28], "Märchenschloss-Hotel zwischen Karstbergen."),
 ("Fanjingshan 梵净山", 27.9100, 108.6917, False, "Tongren, Guizhou", "Tempel",
  [26], "Zwei Tempel auf der Felsnadel „Red Clouds Golden Summit“; ca. 9.000 Stufen (Seilbahn bis fast oben)."),
 # Guangxi
 ("Guilin & Li River 桂林 · 漓江", 25.2780, 110.2911, True, "Guilin, Guangxi", "Natur",
  [4], "Drohnen-Reel „What my drone saw in China“."),
 ("Xingping – Kormoranfischer am Li River 兴坪", 24.9198, 110.5278, True, "Yangshuo, Guangxi", "Dorf",
  [7], "Klassisches Motiv: Fischer mit Kormoranen auf dem Bambusfloß."),
 ("Xianggong Hill 相公山", 24.9258, 110.4790, False, "Yangshuo, Guangxi", "Aussicht",
  [9], "Sonnenaufgang über der Li-River-Schleife – früh los (Wecker 3:30)."),
 ("Yangshuo Karstlandschaft 阳朔", 24.8630, 110.4872, True, "Yangshuo, Guangxi", "Natur",
  [11, 10, 33, (21, 7)], "Karstkegel in endlosen Schichten, Sonnenaufgang mit Wasserbüffeln an der Steinbrücke."),
 ("Longji Rice Terraces 龙脊梯田", 25.7580, 110.1190, True, "Longsheng, Guangxi", "Natur",
  [47, 48, 49, 50], "Rund 650 Jahre alte Reisterrassen, ca. 2 h ab Guilin; im September goldgelb."),
 # Chongqing
 ("Liziba Station 李子坝 – Monorail durchs Haus", 29.5557, 106.5339, False, "Yuzhong, Chongqing", "Architektur",
  [8, 40], "Die Bahn fährt mitten durch das Wohnhaus; Aussichtsplattform unten an der Straße."),
 ("Hongyadong 洪崖洞", 29.565074, 106.575343, False, "Yuzhong, Chongqing", "Neon",
  [(14, 1), (38, 2), (41, 2)], "Abends beleuchtet; viele Treppen. Weitere Tipps im Post: Linhua Road Wohnkomplex, Wulong, Eling-Brücke."),
 ("Qiansimen Bridge 千厮门大桥", 29.565378, 106.576378, False, "Yuzhong, Chongqing", "Neon",
  [20, (38, 4)], "Rote Fachwerkbrücke mit Skyline, nachts."),
 ("Kuixing Building 魁星楼", 29.5633, 106.5699, True, "Jiefangbei, Chongqing", "Architektur",
  [(14, 2)], "Das Erdgeschoss ist zugleich der 22. Stock."),
 ("Linhua Road Residential Complex 临华路", 29.559721, 106.557113, True, "Yuzhong, Chongqing", "Architektur",
  [(14, 4)], "Bunter Spielplatz zwischen Wohntürmen – ruhiger Einblick ins Alltagsleben."),
 ("Eling Park Skywalk 鹅岭栈桥", 29.55246, 106.53204, True, "Yuzhong, Chongqing", "Aussicht",
  [(14, 8)], "Geschwungener Holzsteg am Hang mit Blick auf die Stadt und den Fluss."),
 ("Chongqing Skyline & Rooftops 解放碑", 29.5578, 106.5771, True, "Jiefangbei, Chongqing", "Neon",
  [12, 17, (30, 3), (30, 5), 5, (41, 3)], "Cyberpunk-Blick von Dächern; ab ca. 20 Uhr geht das Licht an."),
 ("Hongen Temple 鸿恩寺", 29.5728, 106.5029, True, "Jiangbei, Chongqing", "Tempel",
  [19], "Laternenweg zur Pagode (Ort nach Bild geschätzt)."),
 ("Three Natural Bridges 天生三桥", 29.4399, 107.7863, False, "Wulong, Chongqing", "Natur",
  [27, (14, 6), (38, 1), (41, 7)], "3 h ab Chongqing; 1 h Rundweg, Glas-Aufzug hinunter. Tagestour: 7 Uhr los, 15 Uhr zurück."),
 ("Baixiangju & Yangtze River Cableway 白象居 · 长江索道", 29.558528, 106.581348, False, "Yuzhong, Chongqing", "Architektur",
  [37, 39, (38, 5)], "Die rote Seilbahn über den Jangtse schwebt zwischen den Wohntürmen hindurch."),
 ("Luohan Temple 罗汉寺", 29.562566, 106.577843, False, "Yuzhong, Chongqing", "Tempel",
  [(38, 3), (41, 6)], "Tausend Jahre alter buddhistischer Tempel mitten zwischen Hochhäusern."),
 ("Chaodong Road 朝东路", 29.566677, 106.584101, True, "Yuzhong, Chongqing", "Street",
  [(38, 6)], "Alltagsstraße mit Blick auf Raffles City."),
 ("Nanbin Road 南滨路", 29.5565, 106.5891, True, "Nan'an, Chongqing", "Aussicht",
  [(41, 5)], "Uferpromenade gegenüber Yuzhong – Nachtblick auf die Skyline."),
 ("The Ring Shopping Mall 光环购物公园", 29.65306, 106.52597, False, "Yubei, Chongqing", "Architektur",
  [(41, 4)], "Einkaufszentrum mit Indoor-Regenwald."),
 # Shanghai
 ("Dongchangzhi Rd × Lushun Rd 东长治路旅顺路", 31.2518, 121.4923, False, "Hongkou, Shanghai", "Street",
  [(21, 3), (46, 3)], "North-Bund-Streetfoto-Spot: Alltag vor Oriental Pearl Tower und Shanghai Tower."),
 ("Waibaidu Bridge & Suzhou Creek 外白渡桥", 31.245307, 121.485744, False, "Huangpu, Shanghai", "Aussicht",
  [22, (35, 2), (36, 2), (46, 7)], "Blick über die Mündung des Suzhou Creek auf Lujiazui zur goldenen Stunde."),
 ("The Bund & Lujiazui 外滩 · 陆家嘴", 31.2402, 121.4979, False, "Huangpu, Shanghai", "Aussicht",
  [(35, 1), 16, (43, 4), (43, 6), (44, 11)], "Skyline abends, wenn alles beleuchtet ist."),
 ("North Bund Riverside Park 北外滩滨江", 31.2500, 121.4990, True, "Hongkou, Shanghai", "Aussicht",
  [(35, 3), 45, (43, 2), (44, 2), (44, 5), (46, 2)], "Uferpark mit Blick auf Lujiazui, morgens ruhig."),
 ("RockBund 外滩源", 31.244389, 121.48416, False, "Huangpu, Shanghai", "Architektur",
  [(35, 5), (43, 8), (46, 6)], "Historische Bauten nördlich des Bund, neugotische Kirche."),
 ("Bvlgari Hotel Shanghai 宝格丽酒店", 31.2455, 121.4805, True, "Suhe, Shanghai", "Aussicht",
  [(35, 6)], "Bar auf der Dachterrasse: Nachtblick auf den Bund und Lujiazui."),
 ("Jiulong Road Waterfront 九龙路", 31.251742, 121.488173, True, "Hongkou, Shanghai", "Architektur",
  [(35, 8), (43, 3), (46, 4)], "Rote Backsteinbauten am Wasser vor der Skyline."),
 ("1000 Trees 天安千树", 31.250871, 121.440889, False, "Putuo, Shanghai", "Architektur",
  [(35, 11), (42, 10), (44, 7), 51], "Heatherwick-Bau mit 1000 Bäumen auf Säulen am Suzhou Creek."),
 ("Jing'an Temple 静安寺", 31.225215, 121.440792, False, "Jing'an, Shanghai", "Tempel",
  [(36, 3)], "Goldener Tempel zwischen Hochhäusern; Blick von der Fußgängerbrücke auf den Verkehr."),
 ("Cathay Cinema 国泰电影院", 31.220119, 121.456793, False, "Xuhui, Shanghai", "Neon",
  [(36, 4)], "Art-déco-Kino von 1932, abends beleuchtet – Langzeitbelichtung mit Rollern."),
 ("China Securities Museum (Pujiang Hotel) 浦江饭店", 31.246393, 121.486633, False, "Hongkou, Shanghai", "Architektur",
  [(36, 5)], "Ehemaliges Astor House Hotel von 1846 an der Waibaidu Bridge."),
 ("The Louis – Louis Vuitton Ship 路易号", 31.230982, 121.458519, True, "Jing'an, Shanghai", "Architektur",
  [(36, 7), (44, 3)], "Schiffsförmiger LV-Pavillon an der West Nanjing Road (bei Xingye Taikoo Hui)."),
 ("Shanghai Tower Observation Deck 上海中心", 31.2356, 121.5012, False, "Lujiazui, Shanghai", "Aussicht",
  [34, (44, 4)], "Sonnenuntergang über Oriental Pearl Tower und Huangpu-Bogen."),
 ("Shanghai Astronomy Museum 上海天文馆", 30.9151, 121.9226, False, "Lingang, Shanghai", "Architektur",
  [18], "Gut 1 h ab Zentrum, 2–4 h einplanen, Kuppel-Show direkt bei Ankunft buchen, vorher essen."),
 ("Museum of Art Pudong 浦东美术馆", 31.240309, 121.491972, False, "Lujiazui, Shanghai", "Architektur",
  [(42, 2)], "Das berühmte „Fenster“ rahmt den Oriental Pearl Tower; Dachterrasse mit Blick auf den Bund."),
 ("Tangqiao Ferry Terminal 塘桥渡口", 31.214906, 121.507075, False, "Pudong, Shanghai", "Aussicht",
  [(42, 3)], "Ruhiger Sonnenuntergangs-Spot mit Lujiazui-Blick, abseits der Bund-Massen."),
 ("Shanghai Juss International Equestrian Center 久事国际马术中心", 31.176686, 121.470652, False, "Pudong, Shanghai", "Architektur",
  [(42, 4)], "Geschwungene Fassade wie eine erstarrte Welle."),
 ("ECEPDI Building 华东电力设计院", 31.2385, 121.4235, True, "Putuo, Shanghai", "Architektur",
  [(42, 5)], "Rostrote Rampe rund um das Bürogebäude (Wuning Road 409)."),
 ("Pacific Xintiandi Observation Hall 太平洋新天地观光厅", 31.2234, 121.476, True, "Huangpu, Shanghai", "Aussicht",
  [(42, 7)], "Bogenfenster mit Blick über die Stadt, kaum Andrang."),
 ("Wukang Mansion 武康大楼", 31.206256, 121.433729, False, "Xuhui, Shanghai", "Architektur",
  [(42, 8)], "Bügeleisen-Bau von 1924 in der ehemaligen Französischen Konzession."),
 ("Yuanmingyuan Road 圆明园路", 31.2433, 121.4836, False, "Huangpu, Shanghai", "Street",
  [(43, 1)], "Fußgängerstraße mit Backsteinbauten und Blick auf den Oriental Pearl Tower."),
 ("The Shanghai EDITION 艾迪逊酒店", 31.239612, 121.481407, False, "Huangpu, Shanghai", "Aussicht",
  [(43, 9)], "Restaurant mit Fensterblick auf Lujiazui."),
 ("Nanjing Road 南京路步行街", 31.237684, 121.475302, True, "Huangpu, Shanghai", "Neon",
  [(46, 5), 44], "Berühmteste Einkaufsstraße Chinas, abends beleuchtet."),
 ("Carlowitz Building 礼和洋行", 31.239142, 121.482069, False, "Huangpu, Shanghai", "Street",
  [(46, 8)], "Backsteinbau hinter dem Edition Hotel – Durchblick zum Oriental Pearl Tower."),
 ("Shanghai Postal Museum 上海邮政博物馆", 31.246407, 121.480755, False, "Hongkou, Shanghai", "Architektur",
  [(46, 9)], "Historisches Postgebäude am Suzhou Creek mit Skyline-Blick."),
 ("Xintiandi 新天地", 31.221931, 121.470437, False, "Huangpu, Shanghai", "Street",
  [44], "Shikumen-Viertel mit Terrassen und Gentle-Monster-Store."),
 ("Yu Garden 豫园", 31.2272, 121.4921, False, "Huangpu, Shanghai", "Tempel",
  [44], "Klassischer chinesischer Garten, eher touristisch."),
 # Weitere
 ("Wangxian Valley 望仙谷", 28.682859, 117.810253, False, "Shangrao, Jiangxi", "Dorf",
  [29, (30, 10), 16], "Klippendorf; am späten Nachmittag kommen, nach Sonnenuntergang beleuchtet. Mit Shanghai kombinierbar (Schnellzug nach Shangrao)."),
 ("Huangshan 黄山", 30.1310, 118.1660, True, "Anhui", "Natur",
  [(30, 6)], ""),
 ("Huanglong National Park 黄龙", 32.7411, 103.8332, False, "Songpan, Sichuan", "Natur",
  [(30, 2), (30, 9)], "Kalksinter-Terrassen in Türkis."),
 ("Chengdu 成都", 30.5728, 104.0668, True, "Sichuan", "Neon",
  [(30, 8), (30, 11), (21, 17)], ""),
 ("Canton Tower 广州塔", 23.108783, 113.317961, False, "Guangzhou", "Neon",
  [(16, 1)], "Skyline am Perlfluss nach Einbruch der Dunkelheit."),
 ("Shenzhen Futian Skyline 平安金融中心", 22.536412, 114.050471, True, "Futian, Shenzhen", "Architektur",
  [25, 16], "Futuristische Skyline nach Einbruch der Dunkelheit; mit Guangzhou kombinierbar."),
 ("Qingdao Haitian Center 青岛海天中心", 36.0562, 120.3649, True, "Shinan, Qingdao", "Neon",
  [23, (21, 15)], "Gedrehter Turm, nachts beleuchtet, Blick vom Strand der Fushan-Bucht."),
 ("Temple of Heaven 天坛", 39.8799, 116.4029, False, "Beijing", "Tempel",
  [(21, 9)], "Halle der Ernteopfer mit blauem Rundtempel-Dach."),
 ("Guge Kingdom Ruins 古格王国遗址", 31.4653, 79.6699, False, "Zanda, Tibet", "Tempel",
  [(21, 11)], "Ruinenstadt im Westen Tibets."),
]

# Beliebtheit 1–5 (5 = Wahrzeichen, 4 = in vielen Guides, 3 = bei Fotografen bekannt)
POP = {
 "Linhua": (2, "Geheimtipp, kaum in Reiseführern"),
 "Eling": (3, "Aussichtspark, bei Fotografen bekannt"),
 "North Bund": (3, "Ruhiger Skyline-Blick abseits des Bund"),
 "RockBund": (4, "Historisches Viertel am Nordende des Bund"),
 "Bvlgari": (3, "Bekannte Rooftop-Bar mit Bund-Blick"),
 "Jiulong": (2, "Geheimtipp für Skyline-Fotos"),
 "1000 Trees": (4, "Viral gewordener Heatherwick-Bau"),
 "Jing'an": (5, "Berühmtester Tempel im Zentrum Shanghais"),
 "Cathay": (3, "Historisches Art-déco-Kino"),
 "Securities": (3, "Astor House, ältestes Hotel Shanghais"),
 "Louis": (4, "Viraler LV-Schiffspavillon 2025"),
 "Zhangjiajie": (5, "Avatar-Berge, eines der bekanntesten Naturziele Chinas"),
 "Tianmen": (5, "Himmelstor & längste Seilbahn, Top-Attraktion"),
 "Furong": (4, "Wasserfall-Dorf, viral in sozialen Medien"),
 "Fenghuang": (5, "Berühmteste Altstadt Westhunans"),
 "Xijiang": (5, "Größtes Miao-Dorf, in allen Guizhou-Guides"),
 "Fenglin": (3, "Bei Fotografen bekannte Karstlandschaft"),
 "Jilong": (3, "Viral gewordenes Schloss-Hotel"),
 "Fanjingshan": (4, "UNESCO-Welterbe, ikonische Felsnadel"),
 "Guilin": (5, "Klassische Karstlandschaft, Li-River-Kreuzfahrt"),
 "Xingping": (4, "Motiv des 20-Yuan-Scheins, Kormoranfischer"),
 "Xianggong": (4, "Bekanntester Sonnenaufgangs-Spot am Li River"),
 "Yangshuo": (5, "Top-Ziel für Karstlandschaften"),
 "Liziba": (5, "Weltbekanntes Fotomotiv Chongqings"),
 "Hongyadong": (5, "Wahrzeichen Chongqings, „Chihiro“-Look"),
 "Qiansimen": (4, "Klassischer Nachtblick auf Hongyadong"),
 "Kuixing": (3, "Kurioses 8D-Gebäude, bei Bloggern beliebt"),
 "Chongqing Skyline": (4, "Cyberpunk-Skyline, viral"),
 "Hongen": (3, "Aussichtspagode über Chongqing"),
 "Three Natural": (5, "UNESCO-Karst, Transformers-Drehort"),
 "Dongchangzhi": (3, "Beliebter Streetfoto-Spot am North Bund"),
 "Waibaidu": (4, "Historische Stahlbrücke mit Skyline-Blick"),
 "The Bund": (5, "Shanghais berühmteste Skyline"),
 "Shanghai Tower": (5, "Höchstes Gebäude Chinas, Aussichtsdeck"),
 "Astronomy": (4, "Größtes Planetarium der Welt"),
 "Wangxian": (4, "Viral gewordenes Klippendorf"),
 "Huangshan": (5, "Berühmtestes Gebirge Chinas, UNESCO"),
 "Huanglong": (5, "UNESCO-Kalksinterterrassen"),
 "Chengdu": (4, "Pandas, Teehäuser, Nachtleben"),
 "Canton Tower": (5, "Wahrzeichen Guangzhous"),
 "Shenzhen": (4, "Moderne Skyline, Ping An Finance Centre"),
 "Qingdao": (3, "Neue Skyline an der Fushan-Bucht"),
 "Temple of Heaven": (5, "UNESCO-Welterbe in Beijing"),
 "Guge": (4, "Abgelegene Ruinenstadt, Fotografen-Traum"),
 "Baixiangju": (4, "Viraler Seilbahn-Fotospot zwischen Wohntürmen"),
 "Luohan": (3, "Historischer Stadttempel, in vielen Chongqing-Guides"),
 "Chaodong": (2, "Alltagsstraße, kaum in Reiseführern"),
 "Nanbin": (4, "Bekannte Uferpromenade mit Nachtblick"),
 "The Ring": (3, "Viral gewordene Regenwald-Mall"),
 "Museum of Art Pudong": (4, "Bekanntes Museum mit ikonischem Fenster-Fotospot"),
 "Tangqiao": (3, "Bei Fotografen beliebter Sonnenuntergangs-Spot"),
 "Equestrian": (2, "Architektur-Geheimtipp in Pudong"),
 "ECEPDI": (2, "Neuer Architektur-Spot, kaum dokumentiert"),
 "Pacific Xintiandi": (2, "Wenig bekannte Aussichtsplattform"),
 "Wukang": (5, "Ikonischer Bau, Shanghais beliebtestes Fotomotiv"),
 "Yuanmingyuan": (3, "Historische Straße, bei Fotografen beliebt"),
 "EDITION": (3, "Luxushotel mit bekanntem Skyline-Blick"),
 "Nanjing Road": (5, "Berühmteste Einkaufsstraße Chinas"),
 "Carlowitz": (2, "Geheimtipp hinter dem Edition Hotel"),
 "Postal Museum": (3, "Historisches Gebäude, in Architekturführern"),
 "Xintiandi": (4, "Bekanntes Shikumen-Ausgehviertel"),
 "Yu Garden": (5, "Klassischer Garten, Top-Sehenswürdigkeit"),
 "Longji": (5, "Berühmteste Reisterrassen Chinas, in allen Guilin-Guides"),
}
