# -*- coding: utf-8 -*-
# Ergänzende Top-Spots, von Claude vorgeschlagen (nicht aus der Instagram-Sammlung).
# (name, Suchbegriff für OSM, Bezirk, Kategorie, Beliebtheit 1–5, Begründung, Wikipedia-Titel, Hinweis)
CLAUDE_SPOTS = [
    ("Avenue of Stars & TST Promenade 星光大道", "Avenue of Stars, Tsim Sha Tsui", "Tsim Sha Tsui", "Aussicht", 5,
     "Klassischer Skyline-Blick, abends Symphony of Lights", "Avenue of Stars, Hong Kong",
     "Skyline von Hong Kong Island; 20:00 Uhr Lichtershow"),
    ("Star Ferry Pier Tsim Sha Tsui 天星碼頭", "Star Ferry Pier, Tsim Sha Tsui", "Tsim Sha Tsui", "Aussicht", 5,
     "Kult-Fähre seit 1888, in jedem Reiseführer", "Star Ferry",
     "Überfahrt nach Central zum Sonnenuntergang"),
    ("Former KCR Clock Tower 尖沙咀鐘樓", "Former Kowloon-Canton Railway Clock Tower", "Tsim Sha Tsui", "Architektur", 4,
     "Wahrzeichen am Hafen, beliebtes Fotomotiv", "Former Kowloon-Canton Railway Clock Tower", ""),
    ("Temple Street Night Market 廟街夜市", "Temple Street, Yau Ma Tei", "Jordan", "Markt", 5,
     "Berühmtester Nachtmarkt Hongkongs", "Temple Street, Hong Kong", "Ab ca. 18 Uhr, Neon & Garküchen"),
    ("Ladies' Market 女人街", "Tung Choi Street, Mong Kok", "Mong Kok", "Markt", 4,
     "Bekanntester Straßenmarkt in Mong Kok", "Ladies' Market", ""),
    ("Man Mo Temple 文武廟", "Man Mo Temple, Hollywood Road", "Sheung Wan", "Tempel", 5,
     "Ikonische Räucherspiralen, in jedem Reiseführer", "Man Mo Temple (Hong Kong Island)",
     "Räucherspiralen von unten mit Lichtstrahlen fotografieren"),
    ("Tai Kwun 大館", "Tai Kwun, Hollywood Road", "Central", "Architektur", 4,
     "Preisgekröntes Kulturzentrum im alten Polizeirevier", "Tai Kwun", ""),
    ("Peak Tram 山頂纜車", "Peak Tram Garden Road Lower Terminus", "Central", "Tram", 5,
     "Historische Standseilbahn, Top-Attraktion", "Peak Tram", "Steilste Fahrt rechts sitzen"),
    ("Sky Terrace 428 / Peak Tower 凌霄閣", "Peak Tower", "The Peak", "Aussicht", 5,
     "Höchste Aussichtsplattform am Peak", "Peak Tower", ""),
    ("Golden Bauhinia Square 金紫荊廣場", "Golden Bauhinia Square", "Wan Chai", "Architektur", 4,
     "Fahnenzeremonie, Wahrzeichen der Übergabe 1997", "Golden Bauhinia Square", "Flaggenzeremonie 8:00 Uhr"),
    ("Hong Kong Observation Wheel 摩天輪", "Hong Kong Observation Wheel", "Central", "Aussicht", 4,
     "Riesenrad am Central Harbourfront", "Hong Kong Observation Wheel", ""),
    ("Blue House 藍屋", "Blue House, Stone Nullah Lane", "Wan Chai", "Architektur", 4,
     "Denkmalgeschütztes Tong Lau, beliebtes Fotomotiv", "Blue House (Hong Kong)", ""),
    ("Happy Valley Racecourse 跑馬地馬場", "Happy Valley Racecourse", "Happy Valley", "Aussicht", 4,
     "Pferderennen mittwochabends inmitten der Hochhäuser", "Happy Valley Racecourse", "Mittwochabend Rennen"),
    ("Sky100 天際100", "International Commerce Centre", "West Kowloon", "Aussicht", 4,
     "Höchste Aussichtsplattform Hongkongs (393 m)", "Sky100", ""),
    ("M+ Museum & West Kowloon Art Park M+", "M+, West Kowloon Cultural District", "West Kowloon", "Architektur", 4,
     "Neues Museum, Sonnenuntergang am Art Park", "M+", "Sonnenuntergang über dem Hafen"),
    ("Hong Kong Palace Museum 香港故宮文化博物館", "Hong Kong Palace Museum", "West Kowloon", "Architektur", 4,
     "Neues Wahrzeichen in West Kowloon", "Hong Kong Palace Museum", ""),
    ("Wong Tai Sin Temple 黃大仙祠", "Wong Tai Sin Temple", "Wong Tai Sin", "Tempel", 5,
     "Meistbesuchter Tempel Hongkongs", "Wong Tai Sin Temple (Hong Kong)", ""),
    ("Chi Lin Nunnery & Nan Lian Garden 志蓮淨苑", "Nan Lian Garden", "Diamond Hill", "Tempel", 4,
     "Goldener Pavillon im Tang-Stil", "Nan Lian Garden", "Goldener Pavillon im Teich"),
    ("Tian Tan Buddha (Big Buddha) 天壇大佛", "Tian Tan Buddha", "Lantau", "Tempel", 5,
     "Weltberühmte Bronzestatue, Top-Attraktion", "Tian Tan Buddha", "Mit Ngong Ping 360 kombinieren"),
    ("Ngong Ping 360 昂坪360", "Ngong Ping 360 Tung Chung Terminal", "Lantau", "Aussicht", 4,
     "Seilbahn mit Glasboden-Kabinen", "Ngong Ping 360", "Crystal Cabin mit Glasboden"),
    ("Ten Thousand Buddhas Monastery 萬佛寺", "Ten Thousand Buddhas Monastery", "Sha Tin", "Tempel", 4,
     "Hunderte goldene Buddha-Statuen am Treppenweg", "Ten Thousand Buddhas Monastery", ""),
    ("Dragon's Back 龍脊", "Dragon's Back", "Shek O", "Aussicht", 4,
     "Beliebteste Stadtwanderung Hongkongs", "Shek O Country Park", "Endet am Big Wave Bay Strand"),
    ("Repulse Bay 淺水灣", "Repulse Bay Beach", "Repulse Bay", "Strand", 4,
     "Bekanntester Stadtstrand, Gebäude mit Loch", "Repulse Bay", "The Repulse Bay Gebäude mit Drachenloch"),
    ("Stanley – Murray House & Blake Pier 赤柱", "Murray House, Stanley", "Stanley", "Dorf", 4,
     "Uferpromenade, Markt, viktorianisches Murray House", "Murray House", ""),
    ("High Island Reservoir East Dam 萬宜水庫東壩", "High Island Reservoir East Dam", "Sai Kung", "Aussicht", 4,
     "UNESCO-Geopark mit sechseckigen Basaltsäulen", "High Island Reservoir", "Taxi ab Sai Kung, kein Bus bis zum Damm"),
    ("Cheung Chau 長洲", "Cheung Chau Ferry Pier", "Cheung Chau", "Dorf", 4,
     "Autofreie Insel, Fischerdorf & Bun Festival", "Cheung Chau", "Fähre ab Central Pier 5"),
]
